import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  // Breakfast
  {
    id: '1',
    name: 'Masala Dosa',
    category: 'breakfast',
    price: 45,
    image: 'https://images.unsplash.com/photo-1665660710687-b44c50751054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb3NhJTIwc291dGglMjBpbmRpYW4lMjBmb29kfGVufDF8fHx8MTc3NDk1MzA4OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Crispy rice crepe filled with spiced potato',
  },
  {
    id: '2',
    name: 'Idli Sambar',
    category: 'breakfast',
    price: 35,
    image: 'https://images.unsplash.com/photo-1730191843435-073792ba22bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpZGxpJTIwc291dGglMjBpbmRpYW4lMjBicmVha2Zhc3R8ZW58MXx8fHwxNzc0OTY2OTMwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Steamed rice cakes served with lentil soup',
  },
  {
    id: '3',
    name: 'Aloo Paratha',
    category: 'breakfast',
    price: 40,
    image: 'https://images.unsplash.com/photo-1759302307381-bdccf7b35e5d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXJhdGhhJTIwaW5kaWFuJTIwYnJlYWR8ZW58MXx8fHwxNzc0OTUyNDgxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Whole wheat bread stuffed with spiced potato',
  },
  // Lunch
  {
    id: '4',
    name: 'Special Veg Thali',
    category: 'lunch',
    price: 85,
    image: 'https://images.unsplash.com/photo-1742281257687-092746ad6021?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbmRpYW4lMjB0aGFsaSUyMG1lYWx8ZW58MXx8fHwxNzc0OTY2OTMxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Complete meal with dal, sabzi, roti, rice & sweet',
  },
  {
    id: '5',
    name: 'Chicken Biryani',
    category: 'lunch',
    price: 120,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiaXJ5YW5pJTIwaW5kaWFuJTIwcmljZXxlbnwxfHx8fDE3NzQ4NTg0MDR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Aromatic basmati rice with tender chicken & spices',
  },
  {
    id: '6',
    name: 'Paneer Tikka Masala',
    category: 'lunch',
    price: 95,
    image: 'https://images.unsplash.com/photo-1666001120694-3ebe8fd207be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYW5lZXIlMjB0aWtrYSUyMGluZGlhbnxlbnwxfHx8fDE3NzQ4NjMyMDR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Grilled cottage cheese in rich tomato gravy',
  },
  {
    id: '7',
    name: 'Vada Pav',
    category: 'lunch',
    price: 30,
    image: 'https://images.unsplash.com/photo-1750767397012-3413ba4fdbc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2YWRhJTIwcGF2JTIwaW5kaWFuJTIwc3RyZWV0fGVufDF8fHx8MTc3NDk2NjkzMXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: false,
    description: 'Mumbai style potato fritter in soft bun',
  },
  // Snacks
  {
    id: '8',
    name: 'Samosa (2 pcs)',
    category: 'snacks',
    price: 25,
    image: 'https://images.unsplash.com/photo-1697155836252-d7f969108b5a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYW1vc2ElMjBpbmRpYW4lMjBzbmFja3xlbnwxfHx8fDE3NzQ4NDE5MTF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Crispy fried pastry with spiced potato filling',
  },
  {
    id: '9',
    name: 'Veg Pakora',
    category: 'snacks',
    price: 30,
    image: 'https://images.unsplash.com/photo-1666190091191-0cd0c5c8c5b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWtvcmElMjBpbmRpYW4lMjBmcml0dGVyfGVufDF8fHx8MTc3NDk2NjkzM3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Mixed vegetable fritters with gram flour',
  },
  {
    id: '10',
    name: 'Gulab Jamun (2 pcs)',
    category: 'snacks',
    price: 35,
    image: 'https://images.unsplash.com/photo-1666190092159-3171cf0fbb12?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxndWxhYiUyMGphbXVuJTIwaW5kaWFuJTIwZGVzc2VydHxlbnwxfHx8fDE3NzQ5NjY5MzN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Sweet milk dumplings in sugar syrup',
  },
  // Beverages
  {
    id: '11',
    name: 'Masala Chai',
    category: 'drinks',
    price: 15,
    image: 'https://images.unsplash.com/photo-1698619952010-3bc850cbcb3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYXNhbGElMjBjaGFpJTIwdGVhfGVufDF8fHx8MTc3NDkyNzY5M3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Traditional Indian spiced tea',
  },
  {
    id: '12',
    name: 'Sweet Lassi',
    category: 'drinks',
    price: 30,
    image: 'https://images.unsplash.com/photo-1637958427185-25a2c0e58419?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXNzaSUyMGluZGlhbiUyMGRyaW5rfGVufDF8fHx8MTc3NDk2NjkzMnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    available: true,
    description: 'Refreshing yogurt-based drink',
  },
];
